apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-deploy-unsecured
  labels:
    tekton.dev/pipeline: build-and-deploy-unsecured
spec:
  params:
    - name: git-revision
      value: master
    - name: IMAGE
      value: 'quay.io/skraft/cosign-acs:base'
    - name: namespace
      value: 'demo'
  pipelineRef:
    name: build-and-deploy-unsecured
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: source-pvc
