apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosign
spec:
  description: >-
    These tasks make it possible to use cosign within your Tekton pipelines
    cosign is a tool for signing and verifying software artifacts.
  params:
    - name: cosignkey
      type: string
    - name: image
      type: string
    - name: namespace
      type: string
  results:
    - description: The email from the certificate common name in JSON format
      name: email
  steps:
    - image: 'gcr.io/projectsigstore/cosign:v2.0.0'
      name: cosign
      resources: {}
      script: >
        #!/busybox/env /busybox/sh

        CMD="cosign sign --key k8s://$(params.namespace)/$(params.cosignkey) $(params.image) --y=true"

        echo "${CMD}"

        ERR_MSG="Failed to sign $(params.image)"

        ${CMD} &> result

        err=$?

        cat result

        if [[ ${err} -ne 0 ]]; then
          echo "${ERR_MSG}"
          exit 1
        fi
      workingDir: /workspace/source
  workspaces:
    - name: source
